/**
 * Client-side report exporters. Everything a report needs already lives on the
 * `HealthReport`, so we build standalone HTML / Markdown strings in the browser and
 * hand them to the user as Blob downloads — no backend round-trip. (PDF is handled
 * separately via the browser's print-to-PDF on the report page.)
 */
import { CATEGORIES, type Category, type HealthReport, type Issue, type Severity } from "../types/contract";

const SEVERITY_ORDER: Severity[] = ["critical", "high", "medium", "low"];

const SEVERITY_LABEL: Record<Severity, string> = {
  critical: "Critical",
  high: "High",
  medium: "Medium",
  low: "Low",
};

/** Hex palette mirroring the app's light theme, inlined so exports are self-contained. */
const SEVERITY_HEX: Record<Severity, { text: string; bg: string; border: string }> = {
  critical: { text: "#e11d48", bg: "rgba(244,63,94,0.10)", border: "rgba(244,63,94,0.30)" },
  high: { text: "#ea580c", bg: "rgba(249,115,22,0.10)", border: "rgba(249,115,22,0.30)" },
  medium: { text: "#d97706", bg: "rgba(245,158,11,0.10)", border: "rgba(245,158,11,0.30)" },
  low: { text: "#0284c7", bg: "rgba(14,165,233,0.10)", border: "rgba(14,165,233,0.30)" },
};

export function scoreHex(score: number): string {
  if (score >= 80) return "#059669";
  if (score >= 60) return "#2563eb";
  if (score >= 40) return "#f59e0b";
  return "#ef4444";
}

/** Sorts issues by severity (critical first) so every export is consistently ordered. */
export function sortIssues(issues: Issue[]): Issue[] {
  return [...issues].sort(
    (a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity)
  );
}

/** Stable identity for an issue (used as React keys and selection-set membership). */
export function issueKey(issue: Issue, index: number): string {
  return `${issue.file}::${issue.line ?? ""}::${index}`;
}

function sourceLine(report: HealthReport): string {
  return `${report.source.type === "github" ? "GitHub" : "ZIP"} · ${report.source.ref}`;
}

/** A filesystem-safe base name like `health-report-user-project-2026-06-29`. */
export function reportFileBase(report: HealthReport): string {
  const slug = report.source.ref
    .replace(/^https?:\/\//, "")
    .replace(/\.git$/, "")
    .replace(/[^a-zA-Z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase()
    .slice(0, 48);
  const date = new Date(report.createdAt).toISOString().slice(0, 10);
  return `health-report-${slug || "project"}-${date}`;
}

export function downloadBlob(filename: string, content: string, mime: string): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

// ---------- Markdown (optimised for an AI to read) ----------

export function buildReportMarkdown(report: HealthReport, issues: Issue[]): string {
  const lines: string[] = [];
  lines.push(`# Project Health Report`, "");
  lines.push(`- **Source:** ${sourceLine(report)}`);
  lines.push(`- **Analyzed:** ${new Date(report.createdAt).toLocaleString()}`);
  lines.push(`- **Report generated:** ${new Date().toLocaleString()}`);
  lines.push(`- **Overall health score:** ${report.overallScore} / 100`);
  lines.push("");

  lines.push(`## Category scores`, "");
  for (const c of CATEGORIES) lines.push(`- **${c}:** ${report.categoryScores[c]} / 100`);
  lines.push("");

  lines.push(`## Issues (${issues.length} selected)`, "");
  if (issues.length === 0) {
    lines.push("_No issues selected for this report._", "");
  } else {
    sortIssues(issues).forEach((issue, i) => {
      const loc = issue.file + (issue.line ? `:${issue.line}` : "");
      lines.push(`### ${i + 1}. [${SEVERITY_LABEL[issue.severity].toUpperCase()}] ${issue.issue}`, "");
      lines.push(`- **File:** \`${loc}\``);
      lines.push(`- **Category:** ${issue.category}`);
      if (issue.analyzer) lines.push(`- **Analyzer:** ${issue.analyzer}`);
      lines.push(`- **Root cause:** ${issue.rootCause}`);
      lines.push(`- **Impact:** ${issue.impact}`);
      lines.push(`- **Suggested fix:** ${issue.solution}`);
      lines.push("");
    });
  }

  lines.push("---", `_Generated by Project Health Inspector._`, "");
  return lines.join("\n");
}

// ---------- Standalone HTML (self-contained document) ----------

function esc(s: string | number): string {
  return String(s)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function categoryRowsHtml(report: HealthReport): string {
  return CATEGORIES.map((c: Category) => {
    const v = report.categoryScores[c];
    return `<div class="cat">
        <div class="cat-head"><span>${esc(c)}</span><span class="cat-val" style="color:${scoreHex(v)}">${v}</span></div>
        <div class="bar"><div class="bar-fill" style="width:${v}%;background:${scoreHex(v)}"></div></div>
      </div>`;
  }).join("");
}

function issueCardsHtml(issues: Issue[]): string {
  if (issues.length === 0) {
    return `<p class="empty">No issues were selected for this report.</p>`;
  }
  return sortIssues(issues)
    .map((issue, i) => {
      const sev = SEVERITY_HEX[issue.severity];
      const loc = esc(issue.file + (issue.line ? `:${issue.line}` : ""));
      return `<article class="issue">
        <div class="issue-top">
          <span class="badge" style="color:${sev.text};background:${sev.bg};border-color:${sev.border}">${SEVERITY_LABEL[issue.severity]}</span>
          <h3>${i + 1}. ${esc(issue.issue)}</h3>
        </div>
        <p class="loc">${loc} <span class="dot">·</span> ${esc(issue.category)}${issue.analyzer ? ` <span class="dot">·</span> ${esc(issue.analyzer)}` : ""}</p>
        <div class="detail-grid">
          <div class="detail"><p class="dl">Root cause</p><p>${esc(issue.rootCause)}</p></div>
          <div class="detail"><p class="dl">Impact</p><p>${esc(issue.impact)}</p></div>
          <div class="detail accent"><p class="dl">Suggested fix</p><p>${esc(issue.solution)}</p></div>
        </div>
      </article>`;
    })
    .join("");
}

export function buildReportHtml(report: HealthReport, issues: Issue[]): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Project Health Report — ${esc(report.source.ref)}</title>
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Anton&family=Plus+Jakarta+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet" />
<style>
  :root { --accent:#2563eb; --ink:#0f172a; --muted:#64748b; --line:rgba(15,23,42,0.08); }
  * { box-sizing:border-box; }
  body {
    margin:0; padding:48px 20px; color:#334155;
    font-family:'Plus Jakarta Sans',system-ui,sans-serif; line-height:1.55;
    background-color:#eef1f8;
    background-image:
      radial-gradient(circle at 50% 0%, rgba(37,99,235,0.10), transparent 55%),
      linear-gradient(rgba(15,23,42,0.045) 1px, transparent 1px),
      linear-gradient(90deg, rgba(15,23,42,0.045) 1px, transparent 1px);
    background-size:100% 100%, 56px 56px, 56px 56px;
  }
  .wrap { max-width:880px; margin:0 auto; }
  .card { background:#fff; border:1px solid var(--line); border-radius:20px; padding:28px;
    box-shadow:0 1px 2px -1px rgba(15,23,42,0.06), 0 20px 44px -32px rgba(15,23,42,0.25); margin-bottom:22px; }
  h1 { font-family:'Anton',sans-serif; font-weight:400; text-transform:uppercase; letter-spacing:-0.01em;
    font-size:40px; line-height:0.95; color:var(--ink); margin:0 0 6px; }
  h2 { font-size:13px; text-transform:uppercase; letter-spacing:0.08em; color:var(--muted); margin:0 0 16px; font-weight:600; }
  .meta { color:var(--muted); font-size:14px; margin:0; }
  .meta b { color:#334155; font-weight:600; }
  .mono { font-family:'JetBrains Mono',monospace; font-size:12.5px; }
  .score-row { display:flex; align-items:center; gap:28px; flex-wrap:wrap; margin-top:18px; }
  .score { font-family:'Anton',sans-serif; font-weight:400; font-size:64px; line-height:1; }
  .score-sub { font-size:11px; text-transform:uppercase; letter-spacing:0.1em; color:var(--muted); }
  .cats { display:grid; grid-template-columns:1fr 1fr; gap:16px 28px; }
  .cat-head { display:flex; justify-content:space-between; font-size:14px; color:#334155; margin-bottom:6px; }
  .cat-val { font-family:'JetBrains Mono',monospace; font-weight:500; }
  .bar { height:6px; border-radius:99px; background:#eef2f7; overflow:hidden; }
  .bar-fill { height:100%; border-radius:99px; }
  .issue { border-top:1px solid var(--line); padding:20px 0; }
  .issue:first-of-type { border-top:0; padding-top:0; }
  .issue-top { display:flex; align-items:flex-start; gap:10px; }
  .issue h3 { margin:0; font-size:15px; color:var(--ink); font-weight:600; }
  .badge { flex:none; font-size:11px; font-weight:600; padding:2px 9px; border-radius:99px; border:1px solid; margin-top:1px; }
  .loc { font-family:'JetBrains Mono',monospace; font-size:12px; color:var(--muted); margin:8px 0 14px; }
  .dot { opacity:0.5; }
  .detail-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:12px; }
  .detail { background:#f8fafc; border:1px solid var(--line); border-radius:12px; padding:12px; }
  .detail.accent { background:rgba(37,99,235,0.05); }
  .dl { font-size:11px; text-transform:uppercase; letter-spacing:0.07em; color:var(--muted); margin:0 0 5px; font-weight:600; }
  .detail p:last-child { margin:0; font-size:13.5px; color:#475569; }
  .empty { color:var(--muted); text-align:center; padding:24px 0; }
  .foot { text-align:center; color:var(--muted); font-size:12px; margin-top:6px; }
  @media (max-width:680px){ .cats,.detail-grid{ grid-template-columns:1fr; } }
</style>
</head>
<body>
  <div class="wrap">
    <section class="card">
      <h1>Project Health Report</h1>
      <p class="meta"><b class="mono">${esc(sourceLine(report))}</b></p>
      <p class="meta">Analyzed ${esc(new Date(report.createdAt).toLocaleString())} · Report generated ${esc(new Date().toLocaleString())}</p>
      <div class="score-row">
        <div>
          <div class="score" style="color:${scoreHex(report.overallScore)}">${report.overallScore}</div>
          <div class="score-sub">Overall health / 100</div>
        </div>
      </div>
    </section>

    <section class="card">
      <h2>Category scores</h2>
      <div class="cats">${categoryRowsHtml(report)}</div>
    </section>

    <section class="card">
      <h2>Issues (${issues.length})</h2>
      ${issueCardsHtml(issues)}
    </section>

    <p class="foot">Generated by Project Health Inspector</p>
  </div>
</body>
</html>`;
}
